//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StronglyTypedApiUrls
{
  public static class ApiUrls
  {
    /// <summary>
    /// ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController
    /// </summary>
    public static class WeatherForecast 
    {
        /// <summary>
        /// The supported HTTP method
        /// </summary>
        public static class HttpGet 
        {
           /// <summary>
           /// api/WeatherForecast
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController System.Collections.Generic.IEnumerable`1[ApiUrlsGenerator.HostedBlazorWasm.Shared.WeatherForecast] Get()</para>
           /// </summary>
           public const string Get = "api/WeatherForecast";

           /// <summary>
           /// api/WeatherForecast/_secretUrl
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController Microsoft.AspNetCore.Mvc.IActionResult SecretUrl()</para>
           /// </summary>
           public const string SecretUrl = "api/WeatherForecast/_secretUrl";

           /// <summary>
           /// api/WeatherForecast/GetSingle/{id:int}
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController ApiUrlsGenerator.HostedBlazorWasm.Shared.WeatherForecast GetSingle(Int32)</para>
           /// </summary>
           public const string GetSingle = "api/WeatherForecast/GetSingle/{id:int}";

        }

        /// <summary>
        /// The supported HTTP method
        /// </summary>
        public static class HttpPost 
        {
           /// <summary>
           /// api/WeatherForecast/NotSecretUrl
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController Microsoft.AspNetCore.Mvc.IActionResult SecretUrl()</para>
           /// </summary>
           public const string SecretUrl = "api/WeatherForecast/NotSecretUrl";

        }

        /// <summary>
        /// The supported HTTP method
        /// </summary>
        public static class HttpAny 
        {
           /// <summary>
           /// api/WeatherForecast
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Controllers.WeatherForecastController Microsoft.AspNetCore.Mvc.ActionResult`1[System.Byte[]] GetBytes()</para>
           /// </summary>
           public const string GetBytes = "api/WeatherForecast";

        }

    }

    /// <summary>
    /// ApiUrlsGenerator.HostedBlazorWasm.Server.Areas.Test.Controllers.WeatherForecastController
    /// </summary>
    public static class TestWeatherForecast 
    {
        /// <summary>
        /// The supported HTTP method
        /// </summary>
        public static class HttpGet 
        {
           /// <summary>
           /// api/Test/WeatherForecast
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Areas.Test.Controllers.WeatherForecastController System.Collections.Generic.IEnumerable`1[ApiUrlsGenerator.HostedBlazorWasm.Shared.WeatherForecast] Get()</para>
           /// </summary>
           public const string Get = "api/Test/WeatherForecast";

           /// <summary>
           /// api/Test/WeatherForecast/_secretUrl
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Areas.Test.Controllers.WeatherForecastController Microsoft.AspNetCore.Mvc.IActionResult SecretUrl()</para>
           /// </summary>
           public const string SecretUrl = "api/Test/WeatherForecast/_secretUrl";

        }

        /// <summary>
        /// The supported HTTP method
        /// </summary>
        public static class HttpAny 
        {
           /// <summary>
           /// api/Test/WeatherForecast
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Areas.Test.Controllers.WeatherForecastController Microsoft.AspNetCore.Mvc.ActionResult`1[System.Byte[]] GetBytes()</para>
           /// </summary>
           public const string GetBytes = "api/Test/WeatherForecast";

           /// <summary>
           /// api/Test/WeatherForecast
           /// <para>ApiUrlsGenerator.HostedBlazorWasm.Server.Areas.Test.Controllers.WeatherForecastController ApiUrlsGenerator.HostedBlazorWasm.Shared.WeatherForecast GetSingle(Int32)</para>
           /// </summary>
           public const string GetSingle = "api/Test/WeatherForecast";

        }

    }

  }
}
