name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.402
    - name: ApiUrlsGenerator.HostedBlazorWasm
      run: dotnet build ./tests/ApiUrlsGenerator.HostedBlazorWasm/Server/ApiUrlsGenerator.HostedBlazorWasm.Server.csproj